apiVersion: v2
name: traefik
description: A Traefik based Kubernetes ingress controller
type: application
version: 20.4.1
appVersion: v2.9.4
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/traefik/traefik
  - https://github.com/wbj3rd/traefik-helm-chart
icon: https://raw.githubusercontent.com/traefik/traefik/v2.3/docs/content/assets/img/traefik.logo.png
annotations:
  artifacthub.io/changes: |
    - Add (optional) dedicated metrics service
